FROM node:20.17.0

WORKDIR /usr/src/app

COPY . .

RUN npm install

RUN npm run build

EXPOSE 3007

COPY entrypoint.sh /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

CMD ["/usr/src/app/entrypoint.sh"]
